// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqhryimtvlnbstpgqvbg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxaHJ5aW10dmxuYnN0cGdxdmJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU5OTM0NDIsImV4cCI6MjA1MTU2OTQ0Mn0.YkDz7ZC5iUYQ1Om1HQYFUtWWyCJn0-KnC19JGQNuIvM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);